import { mcFunction } from "./lib/utils/misc.js";

const functionSellId1 = [#
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 100',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 70',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 20',
  '%scoreboard players add @a[scores={id=1}] coal 1',
];
mcFunction(functionSellId1);
