import { mcFunction } from "./lib/utils/misc.js";

const functionSellId1 = [#
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] diamond 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 40',
  '%scoreboard players add @a[scores={id=1}] diamond 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 200',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] emerald 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 50',
  '%scoreboard players add @a[scores={id=1}] emerald 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] gold_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 8',
  '%scoreboard players add @a[scores={id=1}] gold 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] iron_ingot 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 5',
  '%scoreboard players add @a[scores={id=1}] iron 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] coal 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] coal 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] redstone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] redstone 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] lapis_lazuli 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] lapis 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1',
  'clear @a[scores={id=1}] cobblestone 0 1',
  '%scoreboard players add @a[scores={id=1}] moneytemp 2',
  '%scoreboard players add @a[scores={id=1}] cobblestone 1'
];
mcFunction(functionSellId1);
